baseURL = "https://elixirgraildiary.com/"
languageCode = "en-us"
title = "Elixir Grail Diary"
theme = "ink"
paginate = 25
summaryLength = 50

copyright = "© Copy as I write"

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "G-9ESSW7QXWF"
# disqusShortname = "ink-demo"

[params]
  favicon = "/images/favicon.ico"
	subtitle = "“I wrote them down in my diary so that I wouldn't have to remember.”"

	# Optional 64x64 avatar image.
	avatar = "/images/logo.png"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
  name = "github"
  icon = "github"
  link = "https://github.com/pedro-gaspar"

[[params.social]]
  name = "RSS"
  icon = "rss"
  url = "/index.xml"

[taxonomies]
   tag = "tags"
