baseURL = "https://elixirgraildiary.com"
languageCode = "en-us"
title = "Elixir Grail Diary"
theme = "cactus"
# copyright = "You" # cactus will use title if copyright is not set
# disqusShortname = "example" # Used when comments is enabled. Cactus will use site title if not set
# googleAnalytics = "UA-1234-5"

# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Diary"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[markup]

  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]
  css = ["css/custom.css"]
  colortheme = "white" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  # googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default

  # Home page settings
  description = "<em>(Professor Henry Jones)</em> “Well, he who finds the Grail must face the final challenge.”<br/><em>(Harrison Ford)</em> “What final challenge?”<br/><em>(Professor Henry Jones)</em> “Three devices of such lethal cunning.”<br/><em>(Harrison Ford)</em> “Booby traps?”<br/><em>(Professor Henry Jones)</em> “Oh, yes. But I found the clues that will safely take us through them in the Chronicles of St. Anselm.”<br/><em>(Harrison Ford)</em> “Well, what are they?”<br/><em>(Harrison Ford)</em> “Can't you remember?”<br/><em>(Professor Henry Jones)</em> “I wrote them down in my diary so that I wouldn't have to remember.”"
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.
  showProjectsList = false # show projects list by default (if projects data file exists).
  #projectsUrl = "https://github.com/gohugoio" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = false # default
  showReadTime = false # default

  [params.comments]
    enabled = false # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "twitter"
    link = "https://twitter.com/_pedro_gaspar"

  [[params.social]]
    name = "github"
    link = "https://github.com/pedro-gaspar"

  [[params.social]]
    name = "email"
    link = "pedro.mig.gaspar@gmail.com"

  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/pedromiggaspar/"
